#!/bin/bash
set -e

# Build PHP extra's
# Update conf/ini files and install pecl extensions
#
#${OPENSHIFT_PHP_DIR}/bin/control build

if [ -f ${OPENSHIFT_REPO_DIR}artisan ]
then
	LARAVEL_VERSION=`php ${OPENSHIFT_REPO_DIR}artisan --version`
	echo "Laravel project version $LARAVEL_VERSION already created."
else 
	echo "Installing laravel..."
	composer global require "laravel/installer"
	
	echo "Creating laravel project..."
	pushd ${OPENSHIFT_TMP_DIR}
	composer create-project --prefer-dist laravel/laravel=5.2 ${OPENSHIFT_TMP_DIR}temp12345
	mv ${OPENSHIFT_TMP_DIR}temp12345/* ${OPENSHIFT_REPO_DIR}
	mv ${OPENSHIFT_TMP_DIR}temp12345/.[!.]* ${OPENSHIFT_REPO_DIR}
	LARAVEL_VERSION=`php ${OPENSHIFT_REPO_DIR}artisan --version`
	popd
	rm -rf ${OPENSHIFT_TMP_DIR}temp12345
	echo "Laravel project version $LARAVEL_VERSION successfully installed."
fi
