#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [[ "$OPENSHIFT_PHP_VERSION" != "5.6.16" ]]; then
  echo "ERROR: This quickstart is only compatible with PHP 5.6.16 but current version is $OPENSHIFT_PHP_VERSION"
  echo "ERROR: Please use the https://github.com/boekkooi/openshift-cartridge-php catridge."
  exit 1
fi
